org: jennagracejohnson3
app: lightning-mcqueen
service: lightning-mcqueen-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  deploymentBucket:
    name: team07-lightning-mcqueen-deploy
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
      allowedHeaders:
        - Content-Type
      allowedMethods:
        - GET
        - POST
      allowCredentials: true
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}

functions:
  about:
    handler: handlers/about.handler
    events:
      - httpApi:
          path: /about
          method: get
  login:
    handler: handlers/login.handler
    events:
      - httpApi:
          path: /login
          method: post
      - httpApi:
          path: /api/auth/login
          method: post
  register:
    handler: handlers/register.handler
    events:
      - httpApi:
          path: /register
          method: post
      - httpApi:
          path: /api/auth/register
          method: post
  applicationCreate:
    handler: handlers/applications/create.handler
    events:
      - httpApi:
          path: /api/applications
          method: post
  applicationStatus:
    handler: handlers/applications/status.handler
    events:
      - httpApi:
          path: /api/applications
          method: get